//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoWebProduto.ServiceProduto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produtos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Produtos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        private double PrecoField;
        
        private int EstoqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Estoque {
            get {
                return this.EstoqueField;
            }
            set {
                if ((this.EstoqueField.Equals(value) != true)) {
                    this.EstoqueField = value;
                    this.RaisePropertyChanged("Estoque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProduto.ProdutoServiceSoap")]
    public interface ProdutoServiceSoap {
        
        // CODEGEN: Generating message contract since element name PostResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Post", ReplyAction="*")]
        ConsumoWebProduto.ServiceProduto.PostResponse Post(ConsumoWebProduto.ServiceProduto.PostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Post", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.PostResponse> PostAsync(ConsumoWebProduto.ServiceProduto.PostRequest request);
        
        // CODEGEN: Generating message contract since element name GetProdutosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProdutos", ReplyAction="*")]
        ConsumoWebProduto.ServiceProduto.GetProdutosResponse GetProdutos(ConsumoWebProduto.ServiceProduto.GetProdutosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProdutos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.GetProdutosResponse> GetProdutosAsync(ConsumoWebProduto.ServiceProduto.GetProdutosRequest request);
        
        // CODEGEN: Generating message contract since element name GetProdutoByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProdutoById", ReplyAction="*")]
        ConsumoWebProduto.ServiceProduto.GetProdutoByIdResponse GetProdutoById(ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProdutoById", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.GetProdutoByIdResponse> GetProdutoByIdAsync(ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        ConsumoWebProduto.ServiceProduto.DeleteResponse Delete(ConsumoWebProduto.ServiceProduto.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.DeleteResponse> DeleteAsync(ConsumoWebProduto.ServiceProduto.DeleteRequest request);
        
        // CODEGEN: Generating message contract since element name PutResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Put", ReplyAction="*")]
        ConsumoWebProduto.ServiceProduto.PutResponse Put(ConsumoWebProduto.ServiceProduto.PutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Put", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.PutResponse> PutAsync(ConsumoWebProduto.ServiceProduto.PutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWebProduto.ServiceProduto.PostRequestBody Body;
        
        public PostRequest() {
        }
        
        public PostRequest(ConsumoWebProduto.ServiceProduto.PostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostRequestBody {
        
        public PostRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWebProduto.ServiceProduto.PostResponseBody Body;
        
        public PostResponse() {
        }
        
        public PostResponse(ConsumoWebProduto.ServiceProduto.PostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoWebProduto.ServiceProduto.Produtos PostResult;
        
        public PostResponseBody() {
        }
        
        public PostResponseBody(ConsumoWebProduto.ServiceProduto.Produtos PostResult) {
            this.PostResult = PostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProdutosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProdutos", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWebProduto.ServiceProduto.GetProdutosRequestBody Body;
        
        public GetProdutosRequest() {
        }
        
        public GetProdutosRequest(ConsumoWebProduto.ServiceProduto.GetProdutosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProdutosRequestBody {
        
        public GetProdutosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProdutosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProdutosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWebProduto.ServiceProduto.GetProdutosResponseBody Body;
        
        public GetProdutosResponse() {
        }
        
        public GetProdutosResponse(ConsumoWebProduto.ServiceProduto.GetProdutosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProdutosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoWebProduto.ServiceProduto.Produtos[] GetProdutosResult;
        
        public GetProdutosResponseBody() {
        }
        
        public GetProdutosResponseBody(ConsumoWebProduto.ServiceProduto.Produtos[] GetProdutosResult) {
            this.GetProdutosResult = GetProdutosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProdutoByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProdutoById", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequestBody Body;
        
        public GetProdutoByIdRequest() {
        }
        
        public GetProdutoByIdRequest(ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProdutoByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetProdutoByIdRequestBody() {
        }
        
        public GetProdutoByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProdutoByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProdutoByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWebProduto.ServiceProduto.GetProdutoByIdResponseBody Body;
        
        public GetProdutoByIdResponse() {
        }
        
        public GetProdutoByIdResponse(ConsumoWebProduto.ServiceProduto.GetProdutoByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProdutoByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoWebProduto.ServiceProduto.Produtos GetProdutoByIdResult;
        
        public GetProdutoByIdResponseBody() {
        }
        
        public GetProdutoByIdResponseBody(ConsumoWebProduto.ServiceProduto.Produtos GetProdutoByIdResult) {
            this.GetProdutoByIdResult = GetProdutoByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWebProduto.ServiceProduto.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(ConsumoWebProduto.ServiceProduto.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWebProduto.ServiceProduto.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(ConsumoWebProduto.ServiceProduto.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(string DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Put", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWebProduto.ServiceProduto.PutRequestBody Body;
        
        public PutRequest() {
        }
        
        public PutRequest(ConsumoWebProduto.ServiceProduto.PutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PutRequestBody {
        
        public PutRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWebProduto.ServiceProduto.PutResponseBody Body;
        
        public PutResponse() {
        }
        
        public PutResponse(ConsumoWebProduto.ServiceProduto.PutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoWebProduto.ServiceProduto.Produtos PutResult;
        
        public PutResponseBody() {
        }
        
        public PutResponseBody(ConsumoWebProduto.ServiceProduto.Produtos PutResult) {
            this.PutResult = PutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProdutoServiceSoapChannel : ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoServiceSoapClient : System.ServiceModel.ClientBase<ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap>, ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap {
        
        public ProdutoServiceSoapClient() {
        }
        
        public ProdutoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWebProduto.ServiceProduto.PostResponse ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap.Post(ConsumoWebProduto.ServiceProduto.PostRequest request) {
            return base.Channel.Post(request);
        }
        
        public ConsumoWebProduto.ServiceProduto.Produtos Post() {
            ConsumoWebProduto.ServiceProduto.PostRequest inValue = new ConsumoWebProduto.ServiceProduto.PostRequest();
            inValue.Body = new ConsumoWebProduto.ServiceProduto.PostRequestBody();
            ConsumoWebProduto.ServiceProduto.PostResponse retVal = ((ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap)(this)).Post(inValue);
            return retVal.Body.PostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.PostResponse> ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap.PostAsync(ConsumoWebProduto.ServiceProduto.PostRequest request) {
            return base.Channel.PostAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.PostResponse> PostAsync() {
            ConsumoWebProduto.ServiceProduto.PostRequest inValue = new ConsumoWebProduto.ServiceProduto.PostRequest();
            inValue.Body = new ConsumoWebProduto.ServiceProduto.PostRequestBody();
            return ((ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap)(this)).PostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWebProduto.ServiceProduto.GetProdutosResponse ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap.GetProdutos(ConsumoWebProduto.ServiceProduto.GetProdutosRequest request) {
            return base.Channel.GetProdutos(request);
        }
        
        public ConsumoWebProduto.ServiceProduto.Produtos[] GetProdutos() {
            ConsumoWebProduto.ServiceProduto.GetProdutosRequest inValue = new ConsumoWebProduto.ServiceProduto.GetProdutosRequest();
            inValue.Body = new ConsumoWebProduto.ServiceProduto.GetProdutosRequestBody();
            ConsumoWebProduto.ServiceProduto.GetProdutosResponse retVal = ((ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap)(this)).GetProdutos(inValue);
            return retVal.Body.GetProdutosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.GetProdutosResponse> ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap.GetProdutosAsync(ConsumoWebProduto.ServiceProduto.GetProdutosRequest request) {
            return base.Channel.GetProdutosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.GetProdutosResponse> GetProdutosAsync() {
            ConsumoWebProduto.ServiceProduto.GetProdutosRequest inValue = new ConsumoWebProduto.ServiceProduto.GetProdutosRequest();
            inValue.Body = new ConsumoWebProduto.ServiceProduto.GetProdutosRequestBody();
            return ((ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap)(this)).GetProdutosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWebProduto.ServiceProduto.GetProdutoByIdResponse ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap.GetProdutoById(ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequest request) {
            return base.Channel.GetProdutoById(request);
        }
        
        public ConsumoWebProduto.ServiceProduto.Produtos GetProdutoById(int id) {
            ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequest inValue = new ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequest();
            inValue.Body = new ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequestBody();
            inValue.Body.id = id;
            ConsumoWebProduto.ServiceProduto.GetProdutoByIdResponse retVal = ((ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap)(this)).GetProdutoById(inValue);
            return retVal.Body.GetProdutoByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.GetProdutoByIdResponse> ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap.GetProdutoByIdAsync(ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequest request) {
            return base.Channel.GetProdutoByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.GetProdutoByIdResponse> GetProdutoByIdAsync(int id) {
            ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequest inValue = new ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequest();
            inValue.Body = new ConsumoWebProduto.ServiceProduto.GetProdutoByIdRequestBody();
            inValue.Body.id = id;
            return ((ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap)(this)).GetProdutoByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWebProduto.ServiceProduto.DeleteResponse ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap.Delete(ConsumoWebProduto.ServiceProduto.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public string Delete(int id) {
            ConsumoWebProduto.ServiceProduto.DeleteRequest inValue = new ConsumoWebProduto.ServiceProduto.DeleteRequest();
            inValue.Body = new ConsumoWebProduto.ServiceProduto.DeleteRequestBody();
            inValue.Body.id = id;
            ConsumoWebProduto.ServiceProduto.DeleteResponse retVal = ((ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.DeleteResponse> ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap.DeleteAsync(ConsumoWebProduto.ServiceProduto.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.DeleteResponse> DeleteAsync(int id) {
            ConsumoWebProduto.ServiceProduto.DeleteRequest inValue = new ConsumoWebProduto.ServiceProduto.DeleteRequest();
            inValue.Body = new ConsumoWebProduto.ServiceProduto.DeleteRequestBody();
            inValue.Body.id = id;
            return ((ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWebProduto.ServiceProduto.PutResponse ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap.Put(ConsumoWebProduto.ServiceProduto.PutRequest request) {
            return base.Channel.Put(request);
        }
        
        public ConsumoWebProduto.ServiceProduto.Produtos Put() {
            ConsumoWebProduto.ServiceProduto.PutRequest inValue = new ConsumoWebProduto.ServiceProduto.PutRequest();
            inValue.Body = new ConsumoWebProduto.ServiceProduto.PutRequestBody();
            ConsumoWebProduto.ServiceProduto.PutResponse retVal = ((ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap)(this)).Put(inValue);
            return retVal.Body.PutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.PutResponse> ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap.PutAsync(ConsumoWebProduto.ServiceProduto.PutRequest request) {
            return base.Channel.PutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoWebProduto.ServiceProduto.PutResponse> PutAsync() {
            ConsumoWebProduto.ServiceProduto.PutRequest inValue = new ConsumoWebProduto.ServiceProduto.PutRequest();
            inValue.Body = new ConsumoWebProduto.ServiceProduto.PutRequestBody();
            return ((ConsumoWebProduto.ServiceProduto.ProdutoServiceSoap)(this)).PutAsync(inValue);
        }
    }
}
